version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: contact_list_app_development
      POSTGRES_USER: cleuber
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: cleuber
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: contact_list_app_development
    env_file:
      - .env

volumes:
  postgres_data:
