default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cleuber
  password: 12345678
  host: db

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: contact_list_app_test

production:
  <<: *default
  database: contact_list_app_production
  username: contact_list_app
  password: <%= ENV['CONTACT_LIST_APP_DATABASE_PASSWORD'] %>
